services:
  runtipi-cloudflare-dns-updater:
    build:
      context: shell
      dockerfile: Dockerfile
    container_name: runtipi-cloudflare-dns-updater
    privileged: true
    environment:
      - CF_DNS__DOMAINS_0__NAME=${CF_DNS__DOMAINS_0__NAME}
      - CF_DNS__AUTH__SCOPED_TOKEN=${CF_DNS__AUTH__SCOPED_TOKEN}
      - CF_DNS__ACCOUNTS__SCOPED_ZONE=${CF_DNS__ACCOUNTS__SCOPED_ZONE}
      - CF_DNS__ACCOUNTS__SCOPED_TUNNEL=${CF_DNS__ACCOUNTS__SCOPED_TUNNEL}
      - CF_DNS__DOMAINS_0__PROXIED=${CF_DNS__DOMAINS_0__PROXIED}
    restart: unless-stopped
    networks:
      - tipi_main_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      runtipi.managed: true
