services:
  runtipi-cloudflare-dns-updater:
    build:
      context: shell
      dockerfile: Dockerfile
    container_name: runtipi-cloudflare-dns-updater
    environment:
      - CF_DNS__DOMAINS_0__NAME=${CF_DNS__DOMAINS_0__NAME}
      - CF_DNS__AUTH__SCOPED_TOKEN=${CF_DNS__AUTH__SCOPED_TOKEN}
      - CF_DNS__ACCOUNTS__SCOPED_ZONE=${CF_DNS__ACCOUNTS__SCOPED_ZONE}
      - CF_DNS__ACCOUNTS__SCOPED_TUNNEL=${CF_DNS__ACCOUNTS__SCOPED_TUNNEL}
      - CF_DNS__DOMAINS_0__PROXIED=${CF_DNS__DOMAINS_0__PROXIED}
    restart: unless-stopped
    networks:
      - tipi_main_network
    volumes:
      - ./shell/runtipi_cloudflare_dns_updater.template:/tmp/runtipi_cloudflare_dns_updater.template
      - ./shell/runtipi_cloudflare_dns_updater.sh:/tmp/runtipi_cloudflare_dns_updater.sh
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      runtipi.managed: true
