version: '3.9'

services:
  openflow:
    container_name: openflow
    image: openiap/openflow:1.5.12.35
    restart: unless-stopped
    deploy:
      replicas: 1
    ports:
      - ${APP_PORT}:3000   # internalPort
      - 50051:50051
      - 5858:5858
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
#      mongo-init-replica:
#        condition: service_completed_successfully
    networks:
      - tipi_main_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - protocol=${APP_PROTOCOL}
      - domain=${APP_DOMAIN}
      - auto_hourly_housekeeping=false
      - housekeeping_skip_update_user_size=true
      - housekeeping_skip_calculate_size=true
      - ensure_indexes=false
      - agent_oidc_userinfo_endpoint=http://openflow:${APP_PORT}/oidc/me
      - agent_oidc_issuer=http://${APP_DOMAIN}/oidc
      - agent_oidc_authorization_endpoint=http://${APP_DOMAIN}/oidc/auth
      - agent_oidc_token_endpoint=http://openflow:${APP_PORT}/oidc/token
      - amqp_url=amqp://guest:guest@rabbitmq?frameMax=0x2000
      - mongodb_url=mongodb://mongodb:27017/?replicaSet=rs0
      - mongodb_db=openflow
      - aes_secret=${OPENFLOW_AES_SECRET}
      - TZ=${TZ}
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.openflow-web-redirect.redirectscheme.scheme: https
      traefik.http.services.openflow.loadbalancer.server.port: 3000
      # Web
      traefik.http.routers.openflow-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.openflow-insecure.entrypoints: web
      traefik.http.routers.openflow-insecure.service: openflow
      traefik.http.routers.openflow-insecure.middlewares: openflow-web-redirect
      # Websecure
      traefik.http.routers.openflow.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.openflow.entrypoints: websecure
      traefik.http.routers.openflow.service: openflow
      traefik.http.routers.openflow.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.openflow-local-insecure.rule: Host(`openflow.${LOCAL_DOMAIN}`)
      traefik.http.routers.openflow-local-insecure.entrypoints: web
      traefik.http.routers.openflow-local-insecure.service: openflow
      traefik.http.routers.openflow-local-insecure.middlewares: openflow-web-redirect
      # Local domain secure
      traefik.http.routers.openflow-local.rule: Host(`openflow.${LOCAL_DOMAIN}`)
      traefik.http.routers.openflow-local.entrypoints: websecure
      traefik.http.routers.openflow-local.service: openflow
      traefik.http.routers.openflow-local.tls: true
      runtipi.managed: true

  mongodb:
    container_name: mongodb
    image: mongo:4.4
    restart: unless-stopped
    networks:
      - tipi_main_network
    volumes:
      - ${APP_DATA_DIR}/data/mongo:/data/db
    environment:
      - MONGO_REPLICA_SET_NAME=rs0
      - MONGO_INITDB_DATABASE=openflow
      - TZ=${TZ}
    command: "--bind_ip_all --replSet rs0"
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.adminCommand({ ping: 1 }).ok' | mongo --quiet 127.0.0.1:27017 | grep 1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    labels:
      runtipi.managed: true

  mongo-init-replica:
    image: mongo:4.4
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - tipi_main_network
    restart: "no"
    command: >
      sh -c '
        echo "$(date "+%F %T") Waiting for MongoDB to respond...";
        until mongo --host mongodb:27017 --quiet --eval "db.runCommand({ ping: 1 })" >/dev/null 2>&1; do
          sleep 2;
        done;
        echo "$(date "+%F %T") Initiating replica set (idempotent)...";
        mongo --host mongodb:27017 --quiet --eval "
          try {
            rs.initiate({_id:\"rs0\", members:[{_id:0, host:\"mongodb:27017\"}]})
          } catch(e) {
            if (e.code != 23) { throw e } // 23 = AlreadyInitialized
          }
        ";
        echo "$(date "+%F %T") Waiting for PRIMARY election...";
        until mongo --host mongodb:27017 --quiet --eval "db.isMaster().ismaster" | grep -q true; do
          sleep 1;
        done;
        echo "$(date "+%F %T") Replica set ready (PRIMARY)."
      '
      
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
